# Build configuration for Tea CI, https://www.tea-ci.org

matrix:
  BITS:
    - 32
    - 64
  DEBUG:
    - 0
    - 1

build:
  image: teaci/msys$$BITS
  shell: mingw$$BITS
  commands:
    - make commit-id
    - make main QUIET=1
    - make check
