# use container-based infrastructure
sudo: false

language: c

env:
  global:
    - QUIET=1
  matrix:
    - BITS=32 DEBUG=0
    - BITS=32 DEBUG=1
    - BITS=64 DEBUG=0
    - BITS=64 DEBUG=1

addons:
  apt:
    packages:
      - gcc-multilib

# build using the Makefile
script:
  - make commit-id
  - make main
  - make check

# turn off email notifications
notifications:
  - email: false
