# use container-based infrastructure
sudo: false

language: c

env:
  matrix:
    - BITS=32
    - BITS=64

addons:
  apt:
    packages:
      - gcc-multilib

# build using the Makefile
script:
  - make commit-id
  - make main
  - make check

# turn off email notifications
notifications:
  - email: false
